Cora:
  learning_rate: 0.0001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.3
  tau: 0.4
  num_epochs: 600
  weight_decay: 0.000001
  drop_scheme: 'degree'
  k_neighbors: 2
  rand_layers: 4
  K_layers: 8

PubMed:
  learning_rate: 0.003
  num_hidden: 512
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.5
  tau: 0.8
  num_epochs: 2000
  weight_decay: 0.000001
  drop_scheme: 'degree'
  k_neighbors: 2
  rand_layers: 4
  K_layers: 8

CiteSeer:
  learning_rate: 0.00005
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_embedding: 0.4
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.3
  rand_layers: 2
  tau: 0.8
  num_epochs: 1200
  weight_decay: 0.00001
  drop_scheme: 'degree'
  K_layers: 4
  k_neighbors: 1

Amazon-Computers:
   learning_rate: 0.02
   num_hidden: 256
   num_proj_hidden: 256
   activation: "relu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.2
   drop_edge_rate_2: 0.7
   drop_feature_rate_1: 0.2
   drop_feature_rate_2: 0.2
   tau: 0.3
   num_epochs: 4000
   weight_decay: 0.000001
   drop_scheme: 'degree'
   rand_layers: 2
Amazon-Photo:
   learning_rate: 0.003
   num_hidden: 1024
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.10
   drop_edge_rate_1: 0.6
   drop_edge_rate_2: 0.6
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.3
   tau: 0.3
   k_layers: 4
   k_neighbors: 2
   num_epochs: 3000
   weight_decay: 0.000000
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-CS1:
   learning_rate: 0.0005
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.3
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.2
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.4
   tau: 0.4
   num_epochs: 1000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-CS:
   learning_rate: 0.0005
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_embedding: 0.3
   drop_edge_rate_1: 0.4
   drop_edge_rate_2: 0.4
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.4
   tau: 0.4
   num_epochs: 2000
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 4
Coauthor-Phy:
   learning_rate: 0.01
   num_hidden: 128
   num_proj_hidden: 64
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.4
   drop_edge_rate_2: 0.1
   drop_feature_rate_1: 0.1
   drop_feature_rate_2: 0.4
   tau: 0.5
   num_epochs: 1500
   weight_decay: 0.00001
   drop_scheme: 'degree'
   rand_layers: 4
